# Definitive cloudbuild.yaml - Version 3.0 (Corrected)
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/aura-engine-repo/aura-service:final'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/aura-engine-repo/aura-service:final'

options:
  machineType: 'E2_HIGHCPU_8'

timeout: 3600s